name: slack_plugin
version: 0.0.1
language:
description: slack plugin, send json to slack to notificate some people ...
tags:
 - slack
 - plugin

public: true

# clone_in_docker: false

inputs:
  - name: FLOW_SLACK_INCOMING_URL
    desc_cn: "slack webhook 地址"
    editable: true

  - name: FLOW_SLACK_MSG_JSON
    desc_cn: "slack 发送的 JSON 值"
    editable: true

outputs:

script_path: ./run.sh
